extends: default

rules:
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
  line-length:
    max: 120
  comments:
    min-spaces-from-content: 1
  trailing-spaces: disable
  new-line-at-end-of-file: disable
  