AWSTemplateFormatVersion: '2010-09-09'
Description: 'TaskManager GitHub Actions IAM User and Permissions Setup'

Parameters:
  UserName:
    Type: String
    Default: 'taskmanager-github-actions'
    Description: 'Name for the GitHub Actions IAM user'

Resources:
  # IAM User for GitHub Actions
  GitHubActionsUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      Tags:
        - Key: Purpose
          Value: 'GitHub Actions Deployment'
        - Key: Application
          Value: 'TaskManager'

  # Custom IAM Policy with specific permissions
  TaskManagerDeploymentPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: 'TaskManagerDeploymentPolicy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # CloudFormation permissions
          - Effect: Allow
            Action:
              - cloudformation:*
            Resource: '*'
          
          # Lambda permissions
          - Effect: Allow
            Action:
              - lambda:*
            Resource: '*'
          
          # API Gateway permissions
          - Effect: Allow
            Action:
              - apigateway:*
            Resource: '*'
          
          # RDS permissions
          - Effect: Allow
            Action:
              - rds:*
            Resource: '*'
          
          # VPC permissions
          - Effect: Allow
            Action:
              - ec2:*
            Resource: '*'
          
          # Secrets Manager permissions
          - Effect: Allow
            Action:
              - secretsmanager:*
            Resource: '*'
          
          # CloudWatch permissions
          - Effect: Allow
            Action:
              - logs:*
              - cloudwatch:*
            Resource: '*'
          
          # IAM permissions (limited to what's needed)
          - Effect: Allow
            Action:
              - iam:CreateRole
              - iam:DeleteRole
              - iam:GetRole
              - iam:PassRole
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
              - iam:PutRolePolicy
              - iam:DeleteRolePolicy
              - iam:GetRolePolicy
              - iam:ListRolePolicies
              - iam:ListAttachedRolePolicies
              - iam:CreateInstanceProfile
              - iam:DeleteInstanceProfile
              - iam:AddRoleToInstanceProfile
              - iam:RemoveRoleFromInstanceProfile
              - iam:GetInstanceProfile
              - iam:ListInstanceProfiles
              - iam:TagRole
              - iam:UntagRole
            Resource: 
              - !Sub 'arn:aws:iam::${AWS::AccountId}:role/TaskManager-*'
              - !Sub 'arn:aws:iam::${AWS::AccountId}:instance-profile/TaskManager-*'
          
          # S3 permissions (for SAM deployment)
          - Effect: Allow
            Action:
              - s3:*
            Resource: '*'
          
          # SNS permissions (for notifications)
          - Effect: Allow
            Action:
              - sns:*
            Resource: '*'
          
          # Additional permissions for CloudFormation
          - Effect: Allow
            Action:
              - sts:GetCallerIdentity
              - sts:AssumeRole
            Resource: '*'
      Users:
        - !Ref GitHubActionsUser

  # Access Key for GitHub Actions
  GitHubActionsAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref GitHubActionsUser

Outputs:
  UserName:
    Description: 'IAM User name for GitHub Actions'
    Value: !Ref GitHubActionsUser
    Export:
      Name: 'TaskManager-GitHubActionsUser'

  AccessKeyId:
    Description: 'Access Key ID for GitHub Actions (add to GitHub secrets)'
    Value: !Ref GitHubActionsAccessKey

  SecretAccessKey:
    Description: 'Secret Access Key for GitHub Actions (add to GitHub secrets)'
    Value: !GetAtt GitHubActionsAccessKey.SecretAccessKey

  UserArn:
    Description: 'IAM User ARN'
    Value: !GetAtt GitHubActionsUser.Arn

  PolicyArn:
    Description: 'Custom policy ARN'
    Value: !Ref TaskManagerDeploymentPolicy

  SetupInstructions:
    Description: 'Instructions for GitHub Secrets setup'
    Value: !Sub |
      Add these to your GitHub repository secrets:
      AWS_ACCESS_KEY_ID=${GitHubActionsAccessKey}
      AWS_SECRET_ACCESS_KEY=${GitHubActionsAccessKey.SecretAccessKey}
      
      Also add:
      DATABASE_PASSWORD=your-secure-password
      GOOGLE_CLIENT_ID=your-google-client-id
      GOOGLE_CLIENT_SECRET=your-google-client-secret