---
AWSTemplateFormatVersion: 2010-09-09
Description: TaskManager Global Infrastructure - IAM, Aurora Global Database,
  Secrets Manager
Parameters:
  DatabasePassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Password for the Aurora MySQL database
  EngineVersion:
    Type: String
    Description: Aurora MySQL engine version for the global cluster
  GitHubActionsUserArn:
    Type: String
    Description: ARN of the GitHub Actions IAM user from IAM setup stack
Resources:
  GitHubActionsServiceLinkedRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: TaskManager-GitHubActions-ServiceLinkedRole-Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - iam:GetRole
              - iam:CreateServiceLinkedRole
              - iam:DeleteServiceLinkedRole
            Resource: arn:aws:iam::*:role/aws-service-role/*
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: arn:aws:iam::*:role/TaskManager-*
      Roles:
        - !Ref SharedLambdaExecutionRole
  ECSCleanupFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub taskmanager-ecs-role-setup-${AWS::StackName}
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt SharedLambdaExecutionRole.Arn
      Code:
        ZipFile: >
          import boto3

          import json

          import logging


          logger = logging.getLogger()

          logger.setLevel(logging.INFO)


          iam_client = boto3.client('iam')


          def lambda_handler(event, context):
              try:
                  request_type = event.get('RequestType')

                  logger.info(f"Processing {request_type} for ECS service-linked role")

                  if request_type == 'Create':
                      # Try to create ECS service-linked role if it doesn't exist
                      create_ecs_service_linked_role()

                      # Send success response
                      send_response(event, context, 'SUCCESS', {'Message': 'ECS service-linked role setup complete'})
                  else:
                      # For Update/Delete, just succeed
                      send_response(event, context, 'SUCCESS', {'Message': 'ECS service-linked role unchanged'})

              except Exception as e:
                  logger.error(f"Error processing request: {str(e)}")
                  send_response(event, context, 'SUCCESS', {'Message': f'Handled gracefully: {str(e)}'})

          def create_ecs_service_linked_role():
              try:
                  role_name = 'AWSServiceRoleForECS'
                  service_name = 'ecs.amazonaws.com'

                  # Check if the role already exists
                  try:
                      iam_client.get_role(RoleName=role_name)
                      logger.info(f"ECS service-linked role {role_name} already exists")
                      return
                  except iam_client.exceptions.NoSuchEntityException:
                      logger.info(f"ECS service-linked role {role_name} does not exist, creating...")

                  # Create the service-linked role
                  iam_client.create_service_linked_role(
                      AWSServiceName=service_name,
                      Description='Service-linked role for Amazon ECS'
                  )
                  logger.info(f"Successfully created ECS service-linked role {role_name}")

              except Exception as e:
                  logger.warning(f"Could not create ECS service-linked role: {str(e)}")
                  # Don't fail - the role might already exist or we might not have permissions

          def send_response(event, context, response_status, response_data):
              import urllib.request
              import json

              response_url = event.get('ResponseURL')
              if not response_url:
                  return

              response_body = {
                  'Status': response_status,
                  'Reason': response_data.get('Message', 'Operation completed'),
                  'PhysicalResourceId': event.get('PhysicalResourceId', context.log_stream_name),
                  'StackId': event['StackId'],
                  'RequestId': event['RequestId'],
                  'LogicalResourceId': event['LogicalResourceId'],
                  'Data': response_data
              }

              json_response_body = json.dumps(response_body)

              headers = {
                  'Content-Type': '',
                  'Content-Length': str(len(json_response_body))
              }

              req = urllib.request.Request(response_url, data=json_response_body.encode('utf-8'), headers=headers, method='PUT')
              try:
                  with urllib.request.urlopen(req) as response:
                      logger.info(f"Response sent: {response.status}")
              except Exception as e:
                  logger.error(f"Failed to send response: {str(e)}")
      Tags:
        - Key: Stack
          Value: !Ref "AWS::StackName"
  ECSRoleSetupResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt ECSCleanupFunction.Arn
    DependsOn:
      - SharedLambdaExecutionRole
      - ECSCleanupFunction
  SharedLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub TaskManager-Shared-Lambda-Role-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                Resource:
                  - !Sub arn:aws:secretsmanager:us-east-1:${AWS::AccountId}:secret:taskmanager/database/regional/us-east-1*
                  - !Sub arn:aws:secretsmanager:us-east-2:${AWS::AccountId}:secret:taskmanager/database/regional/us-east-2*
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:us-east-1:${AWS::AccountId}:*
                  - !Sub arn:aws:logs:us-east-2:${AWS::AccountId}:*
        - PolicyName: RDSAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - rds:CreateDBCluster
                  - rds:ModifyDBCluster
                  - rds:DeleteDBCluster
                  - rds:DescribeDBClusters
                  - rds:DescribeDBInstances
                  - rds:DescribeGlobalClusters
                  - rds:ModifyGlobalCluster
                  - rds:DeleteGlobalCluster
                  - rds-data:ExecuteStatement
                  - rds-data:BatchExecuteStatement
                Resource:
                  - !Sub arn:aws:rds:us-east-1:${AWS::AccountId}:cluster:taskmanager-*
                  - !Sub arn:aws:rds:us-east-2:${AWS::AccountId}:cluster:taskmanager-*
                  - !Sub arn:aws:rds::${AWS::AccountId}:global-cluster:taskmanager-global-cluster
        - PolicyName: KMSAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - kms:CreateKey
                  - kms:DescribeKey
                  - kms:CreateGrant
                  - kms:Decrypt
                  - kms:Encrypt
                  - kms:GenerateDataKey
                  - kms:ReEncryptFrom
                  - kms:ReEncryptTo
                  - kms:RetireGrant
                  - kms:CreateAlias
                  - kms:DeleteAlias
                  - kms:UpdateAlias
                  - kms:ListAliases
                  - kms:ListGrants
                  - kms:RevokeGrant
                  - kms:ReplicateKey
                Resource: "*"
      Tags:
        - Key: Stack
          Value: !Ref "AWS::StackName"
  BastionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub TaskManager-Bastion-Role-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: SecretsManagerRead
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Sub arn:aws:secretsmanager:us-east-1:${AWS::AccountId}:secret:taskmanager/database/regional/us-east-1*
                  - !Sub arn:aws:secretsmanager:us-east-2:${AWS::AccountId}:secret:taskmanager/database/regional/us-east-2*
      Tags:
        - Key: Stack
          Value: !Ref "AWS::StackName"
  BastionInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref BastionRole
  AuroraKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Multi-region KMS key for Aurora Global Database encryption
      KeyUsage: ENCRYPT_DECRYPT
      KeySpec: SYMMETRIC_DEFAULT
      MultiRegion: true
      Enabled: true
      PendingWindowInDays: 7
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: EnableIAMUserPermissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: "*"
          - Sid: AllowRDSService
            Effect: Allow
            Principal:
              Service: rds.amazonaws.com
            Action:
              - kms:CreateGrant
              - kms:DescribeKey
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:ReEncryptFrom
              - kms:ReEncryptTo
              - kms:RetireGrant
            Resource: "*"
          - Sid: AllowGitHubActionsUser
            Effect: Allow
            Principal:
              AWS: !Ref GitHubActionsUserArn
            Action:
              - kms:CreateKey
              - kms:DescribeKey
              - kms:CreateGrant
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:ReEncryptFrom
              - kms:ReEncryptTo
              - kms:RetireGrant
              - kms:CreateAlias
              - kms:DeleteAlias
              - kms:UpdateAlias
              - kms:ListAliases
              - kms:ListGrants
              - kms:RevokeGrant
            Resource: "*"
      Tags:
        - Key: Stack
          Value: !Ref "AWS::StackName"
  AuroraGlobalCluster:
    Type: AWS::RDS::GlobalCluster
    Properties:
      GlobalClusterIdentifier: taskmanager-global-cluster
      Engine: aurora-mysql
      EngineVersion: !Ref EngineVersion
      DeletionProtection: false
      StorageEncrypted: true
      Tags:
        - Key: Stack
          Value: !Ref "AWS::StackName"
Outputs:
  SharedLambdaRoleArn:
    Description: Shared Lambda execution role ARN
    Value: !GetAtt SharedLambdaExecutionRole.Arn
    Export:
      Name: TaskManager-SharedLambdaRole
  BastionRoleArn:
    Description: Bastion role ARN
    Value: !GetAtt BastionRole.Arn
    Export:
      Name: TaskManager-BastionRole
  BastionInstanceProfileArn:
    Description: Bastion instance profile ARN
    Value: !Ref BastionInstanceProfile
    Export:
      Name: TaskManager-BastionInstanceProfile
  AuroraGlobalClusterId:
    Description: Aurora Global Database cluster identifier
    Value: !Ref AuroraGlobalCluster
    Export:
      Name: TaskManager-AuroraGlobalCluster
  AuroraKmsKeyArn:
    Description: KMS key ARN used for Aurora encryption
    Value: !GetAtt AuroraKmsKey.Arn
    Export:
      Name: TaskManager-AuroraKmsKey
