---
AWSTemplateFormatVersion: "2010-09-09"
Description: "TaskManager Master Infrastructure Template - Includes all regional components and applications"

Parameters:
  # Common parameters
  TemplateBucket:
    Type: String
    Description: S3 bucket name containing the CloudFormation templates

  GitHubActionsUserArn:
    Type: String
    Description: ARN of the GitHub Actions IAM user

  BranchName:
    Type: String
    Description: Branch name for resource naming

  DatabasePassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Password for the Aurora MySQL database

  EngineVersion:
    Type: String
    Description: Aurora MySQL engine version

  # Region-specific parameters
  IsPrimaryRegion:
    Type: String
    AllowedValues: ["true", "false"]
    Description: Whether this region hosts the primary cluster

  # Parameters for global infrastructure outputs
  AuroraGlobalClusterId:
    Type: String
    Default: ""
    Description: ID of the Aurora global cluster

  ApiGatewayCloudWatchLogsRoleArn:
    Type: String
    Default: ""
    Description: ARN of the API Gateway CloudWatch Logs role

  SharedLambdaRoleArn:
    Type: String
    Default: ""
    Description: ARN of the shared Lambda role

  # Parameters for secondary regions
  KmsKeyArn:
    Type: String
    Description: ARN of the primary KMS key (for secondary regions)
    Default: ""

  # Google OAuth parameters
  GoogleOAuthClientId:
    Type: String
    Description: Google OAuth Client ID
    NoEcho: true

  GoogleOAuthClientSecret:
    Type: String
    Description: Google OAuth Client Secret
    NoEcho: true

  # Web parameters
  WebContainerImage:
    Type: String
    Description: "Container image URI for the web application"

  DeploymentToken:
    Type: String
    Default: "default"
    Description: "Deployment token to force task definition updates"

  DomainName:
    Type: String
    Default: "appcloud.systems"
    Description: "Domain name for SSL certificate"

  HostedZoneId:
    Type: String
    Description: "Route 53 hosted zone ID for the domain"

Conditions:
  IsPrimary: !Equals [!Ref IsPrimaryRegion, "true"]
  IsSecondary: !Equals [!Ref IsPrimaryRegion, "false"]
  HasKmsKeyArn: !Not [!Equals [!Ref KmsKeyArn, ""]]
  HasGlobalClusterId: !Not [!Equals [!Ref AuroraGlobalClusterId, ""]]

Resources:
  # KMS Key (Primary or Replica)
  KmsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./kms-template.yaml
      Parameters:
        GitHubActionsUserArn: !Ref GitHubActionsUserArn
        BranchName: !Ref BranchName
        KmsKeyArn: !If [HasKmsKeyArn, !Ref KmsKeyArn, !Ref "AWS::NoValue"]
        IsPrimaryRegion: !Ref IsPrimaryRegion

  # Regional VPC
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./regional-vpc.yaml
      Parameters:
        BranchName: !Ref BranchName
        LogRetentionDays: 7

  # Regional Database
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [KmsStack, VpcStack]
    Properties:
      TemplateURL: ./regional-db.yaml
      Parameters:
        DatabasePassword: !Ref DatabasePassword
        EngineVersion: !Ref EngineVersion
        AuroraGlobalClusterId: !Ref AuroraGlobalClusterId
        AuroraKmsKeyArn: !GetAtt KmsStack.Outputs.AuroraKmsKeyArn
        IsPrimaryRegion: !Ref IsPrimaryRegion
        GitHubActionsUserArn: !Ref GitHubActionsUserArn
        BranchName: !Ref BranchName
        VPCId: !GetAtt VpcStack.Outputs.VPCId
        PrivateSubnet1Id: !GetAtt VpcStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VpcStack.Outputs.PrivateSubnet2Id
        RDSSecurityGroupId: !GetAtt VpcStack.Outputs.RDSSecurityGroupId
        LogRetentionDays: 7

  # Regional Infrastructure
  InfrastructureStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DatabaseStack
    Properties:
      TemplateURL: ./regional-infrastructure.yaml
      Parameters:
        BranchName: !Ref BranchName
        GoogleOAuthClientId: !Ref GoogleOAuthClientId
        GoogleOAuthClientSecret: !Ref GoogleOAuthClientSecret
        ApiGatewayCloudWatchLogsRoleArn: !Ref ApiGatewayCloudWatchLogsRoleArn

  # Regional API
  ApiStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [InfrastructureStack, DatabaseStack]
    Properties:
      TemplateURL: ./api-template.yaml
      Parameters:
        Environment: !Ref BranchName
        SharedLambdaRoleArn: !Ref SharedLambdaRoleArn
        DatabaseHost: !GetAtt DatabaseStack.Outputs.DatabaseHost
        DatabaseUsername: !GetAtt DatabaseStack.Outputs.DatabaseUsername
        DatabaseEngine: !GetAtt DatabaseStack.Outputs.DatabaseEngine
        DatabasePort: !GetAtt DatabaseStack.Outputs.DatabasePort
        DatabaseName: !GetAtt DatabaseStack.Outputs.DatabaseName
        DatabaseClusterArn: !GetAtt DatabaseStack.Outputs.DatabaseClusterArn
        LambdaSecurityGroupId: !GetAtt VpcStack.Outputs.LambdaSecurityGroupId
        PrivateSubnet1Id: !GetAtt VpcStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VpcStack.Outputs.PrivateSubnet2Id
        LogRetentionDays: 7

  # Regional Web
  WebStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [InfrastructureStack, DatabaseStack]
    Properties:
      TemplateURL: ./web-template.yaml
      Parameters:
        Environment: !Ref BranchName
        WebContainerImage: !Ref WebContainerImage
        DeploymentToken: !Ref DeploymentToken
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        SharedLambdaRoleArn: !Ref SharedLambdaRoleArn
        VPCId: !GetAtt VpcStack.Outputs.VPCId
        ALBSecurityGroupId: !GetAtt VpcStack.Outputs.ALBSecurityGroupId
        ECSTaskSecurityGroupId: !GetAtt VpcStack.Outputs.ECSTaskSecurityGroupId
        PublicSubnet1Id: !GetAtt VpcStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt VpcStack.Outputs.PublicSubnet2Id
        PrivateSubnet1Id: !GetAtt VpcStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VpcStack.Outputs.PrivateSubnet2Id
        ECSClusterName: !GetAtt InfrastructureStack.Outputs.ECSClusterName
        GoogleOAuthSecretArn: !GetAtt InfrastructureStack.Outputs.GoogleOAuthSecretArn
        DatabaseHost: !GetAtt DatabaseStack.Outputs.DatabaseHost
        DatabaseUsername: !GetAtt DatabaseStack.Outputs.DatabaseUsername
        DatabaseEngine: !GetAtt DatabaseStack.Outputs.DatabaseEngine
        DatabasePort: !GetAtt DatabaseStack.Outputs.DatabasePort
        DatabaseName: !GetAtt DatabaseStack.Outputs.DatabaseName
        DatabaseClusterArn: !GetAtt DatabaseStack.Outputs.DatabaseClusterArn
        DatabasePasswordSecretArn: !GetAtt DatabaseStack.Outputs.DatabasePasswordSecretArn
        LogRetentionDays: 7

Outputs:
  # KMS outputs
  AuroraKmsKeyArn:
    Description: ARN of the KMS key
    Value: !GetAtt KmsStack.Outputs.AuroraKmsKeyArn

  # Global outputs
  AuroraGlobalClusterId:
    Description: ID of the Aurora global cluster
    Value:
      !If [
        IsPrimary,
        !GetAtt DatabaseStack.Outputs.AuroraGlobalClusterId,
        !Ref AuroraGlobalClusterId,
      ]

  ApiGatewayCloudWatchLogsRoleArn:
    Description: ARN of the API Gateway CloudWatch Logs role
    Value: !Ref ApiGatewayCloudWatchLogsRoleArn

  SharedLambdaRoleArn:
    Description: ARN of the shared Lambda role
    Value: !Ref SharedLambdaRoleArn

  # Database outputs
  DatabaseEndpoint:
    Description: Aurora MySQL cluster endpoint
    Value: !GetAtt DatabaseStack.Outputs.DatabaseEndpoint

  DatabaseReaderEndpoint:
    Description: Aurora MySQL reader endpoint
    Value: !GetAtt DatabaseStack.Outputs.DatabaseReaderEndpoint

  DatabaseUsername:
    Description: Database username
    Value: !GetAtt DatabaseStack.Outputs.DatabaseUsername

  DatabaseEngine:
    Description: Database engine
    Value: !GetAtt DatabaseStack.Outputs.DatabaseEngine

  DatabaseHost:
    Description: Database host endpoint
    Value: !GetAtt DatabaseStack.Outputs.DatabaseHost

  DatabasePort:
    Description: Database port
    Value: !GetAtt DatabaseStack.Outputs.DatabasePort

  DatabaseName:
    Description: Database name
    Value: !GetAtt DatabaseStack.Outputs.DatabaseName

  DatabaseClusterArn:
    Description: Database cluster ARN
    Value: !GetAtt DatabaseStack.Outputs.DatabaseClusterArn

  DatabasePasswordSecretArn:
    Description: Database password secret ARN
    Value: !GetAtt DatabaseStack.Outputs.DatabasePasswordSecretArn

  # VPC outputs
  VpcId:
    Description: VPC ID
    Value: !GetAtt VpcStack.Outputs.VPCId

  PrivateSubnet1Id:
    Description: Private subnet 1 ID
    Value: !GetAtt VpcStack.Outputs.PrivateSubnet1Id

  PrivateSubnet2Id:
    Description: Private subnet 2 ID
    Value: !GetAtt VpcStack.Outputs.PrivateSubnet2Id

  PublicSubnet1Id:
    Description: Public subnet 1 ID
    Value: !GetAtt VpcStack.Outputs.PublicSubnet1Id

  PublicSubnet2Id:
    Description: Public subnet 2 ID
    Value: !GetAtt VpcStack.Outputs.PublicSubnet2Id

  LambdaSecurityGroupId:
    Description: Lambda security group ID
    Value: !GetAtt VpcStack.Outputs.LambdaSecurityGroupId

  ALBSecurityGroupId:
    Description: ALB security group ID
    Value: !GetAtt VpcStack.Outputs.ALBSecurityGroupId

  ECSTaskSecurityGroupId:
    Description: ECS task security group ID
    Value: !GetAtt VpcStack.Outputs.ECSTaskSecurityGroupId

  VpcFlowLogsRoleArn:
    Description: VPC Flow Logs role ARN
    Value: !GetAtt VpcStack.Outputs.VpcFlowLogsRoleArn

  # Infrastructure outputs
  ECSClusterName:
    Description: ECS cluster name
    Value: !GetAtt InfrastructureStack.Outputs.ECSClusterName

  GoogleOAuthSecretArn:
    Description: ARN of the Google OAuth secrets
    Value: !GetAtt InfrastructureStack.Outputs.GoogleOAuthSecretArn

  # API outputs
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !GetAtt ApiStack.Outputs.ApiEndpoint

  ApiLambdaFunctionName:
    Description: "API Lambda function name"
    Value: !GetAtt ApiStack.Outputs.ApiLambdaFunctionName

  # Web outputs
  WebEndpoint:
    Description: "Web application endpoint URL"
    Value: !GetAtt WebStack.Outputs.WebEndpoint

  WebLoadBalancerDNS:
    Description: "Web Load Balancer DNS name"
    Value: !GetAtt WebStack.Outputs.WebLoadBalancerDNS

  WebLoadBalancerHostedZoneId:
    Description: "Web Load Balancer hosted zone ID"
    Value: !GetAtt WebStack.Outputs.WebLoadBalancerHostedZoneId

  WebTaskDefinition:
    Description: "Web ECS task definition"
    Value: !GetAtt WebStack.Outputs.WebTaskDefinition

  WebServiceName:
    Description: "Web ECS service name"
    Value: !GetAtt WebStack.Outputs.WebServiceName
