---
AWSTemplateFormatVersion: 2010-09-09
Description: TaskManager Regional KMS Key Replica

Parameters:
  PrimaryKeyArn:
    Type: String
    Description: ARN of the primary multi-region KMS key

  GitHubActionsUserArn:
    Type: String
    Description: ARN of the GitHub Actions IAM user

  BranchName:
    Type: String
    Description: Branch name for resource naming

Resources:
  AuroraKmsKeyReplica:
    Type: AWS::KMS::ReplicaKey
    DeletionPolicy: Retain
    Properties:
      PrimaryKeyArn: !Ref PrimaryKeyArn
      Description: Replica of multi-region Aurora KMS key
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: EnableIAMUserPermissions
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: kms:*
            Resource: "*"
          - Sid: AllowRDSService
            Effect: Allow
            Principal:
              Service: rds.amazonaws.com
            Action:
              - kms:CreateGrant
              - kms:DescribeKey
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:ReEncryptFrom
              - kms:ReEncryptTo
              - kms:RetireGrant
            Resource: "*"
          - Sid: AllowGitHubActionsUser
            Effect: Allow
            Principal:
              AWS: !Ref GitHubActionsUserArn
            Action:
              - kms:CreateKey
              - kms:DescribeKey
              - kms:CreateGrant
              - kms:Decrypt
              - kms:Encrypt
              - kms:GenerateDataKey
              - kms:ReEncryptFrom
              - kms:ReEncryptTo
              - kms:RetireGrant
              - kms:CreateAlias
              - kms:DeleteAlias
              - kms:UpdateAlias
              - kms:ListAliases
              - kms:ListGrants
              - kms:RevokeGrant
            Resource: "*"
      Tags:
        - Key: LogicalId
          Value: AuroraKmsKeyReplica
        - Key: Stack
          Value: !Ref "AWS::StackName"

Outputs:
  AuroraKmsKeyReplicaArn:
    Description: ARN of the KMS key replica
    Value: !GetAtt AuroraKmsKeyReplica.Arn
    Export:
      Name: !Sub "TaskManager-AuroraKmsKeyReplica-${BranchName}-${AWS::Region}"
