---
AWSTemplateFormatVersion: "2010-09-09"
Description: "TaskManager Regional Infrastructure - VPC, RDS, ECS"

Parameters:
  DatabasePassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: "Password for the Aurora MySQL database"

  EngineVersion:
    Type: String
    Description: "Aurora MySQL engine version for the regional cluster"

  AuroraGlobalClusterId:
    Type: String
    Description: "ID of the Aurora global cluster from global stack"

  AuroraKmsKeyArn:
    Type: String
    Description: "ARN of the KMS key used by the Aurora global cluster"

  # Parameters from regional-vpc-db.yaml outputs
  VPCId:
    Type: String
    Description: "VPC ID from regional-vpc-db stack"

  PrivateSubnet1Id:
    Type: String
    Description: "Private subnet 1 ID from regional-vpc-db stack"

  PrivateSubnet2Id:
    Type: String
    Description: "Private subnet 2 ID from regional-vpc-db stack"

  PublicSubnet1Id:
    Type: String
    Description: "Public subnet 1 ID from regional-vpc-db stack"

  PublicSubnet2Id:
    Type: String
    Description: "Public subnet 2 ID from regional-vpc-db stack"

  LambdaSecurityGroupId:
    Type: String
    Description: "Lambda security group ID from regional-vpc-db stack"

  RDSSecurityGroupId:
    Type: String
    Description: "RDS security group ID from regional-vpc-db stack"

  ALBSecurityGroupId:
    Type: String
    Description: "ALB security group ID from regional-vpc-db stack"

  ECSTaskSecurityGroupId:
    Type: String
    Description: "ECS task security group ID from regional-vpc-db stack"

  DatabaseEndpoint:
    Type: String
    Description: "Database endpoint from regional-vpc-db stack"

  DatabaseReaderEndpoint:
    Type: String
    Description: "Database reader endpoint from regional-vpc-db stack"

  SharedLambdaRoleArn:
    Type: String
    Description: "ARN of the shared Lambda role from global stack"

  GoogleOAuthClientId:
    Type: String
    Description: "Google OAuth Client ID"
    NoEcho: true

  GoogleOAuthClientSecret:
    Type: String
    Description: "Google OAuth Client Secret"
    NoEcho: true

  ApiGatewayCloudWatchLogsRoleArn:
    Type: String
    Description: "ARN of the API Gateway CloudWatch Logs role from global stack"

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: "TaskManager-Cluster"
      Tags:
        - Key: LogicalId
          Value: ECSCluster
        - Key: Name
          Value: "TaskManager-ECS-Cluster"
        - Key: Purpose
          Value: "Regional Infrastructure"
        - Key: Stack
          Value: !Ref "AWS::StackName"

  # Google OAuth Secrets
  GoogleOAuthSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "taskmanager/google-oauth/${AWS::StackName}"
      Description: "Google OAuth credentials for TaskManager web application"
      SecretString: !Sub |
        {
          "clientId": "${GoogleOAuthClientId}",
          "clientSecret": "${GoogleOAuthClientSecret}"
        }
      Tags:
        - Key: LogicalId
          Value: GoogleOAuthSecrets
        - Key: Name
          Value: "TaskManager-GoogleOAuth-Secrets"
        - Key: Purpose
          Value: "Google OAuth Configuration"
        - Key: Stack
          Value: !Ref "AWS::StackName"

  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !Ref ApiGatewayCloudWatchLogsRoleArn

Outputs:
  ECSClusterName:
    Description: "ECS cluster name"
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: "TaskManager-ECSCluster"

  GoogleOAuthSecretArn:
    Description: "ARN of the Google OAuth secrets"
    Value: !Ref GoogleOAuthSecrets
    Export:
      Name: !Sub "TaskManager-GoogleOAuthSecretArn-${AWS::StackName}"
