---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Regional S3 bucket and ECR repository setup"

Parameters:
  BranchName:
    Type: String
    Description: "Branch name for resource naming"

Resources:
  WebECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "taskmanager-${BranchName}-web-${AWS::Region}"
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: "MUTABLE"
      Tags:
        - Key: LogicalId
          Value: WebECRRepository
        - Key: Name
          Value: "TaskManager-Web-ECR"
        - Key: Purpose
          Value: "Container Registry"
        - Key: Stack
          Value: !Ref "AWS::StackName"
