AWSTemplateFormatVersion: "2010-09-09"
Description: "Regional S3 bucket setup"

Parameters:
  BranchName:
    Type: String
    Description: "Branch name for resource naming"

Resources:
  RegionalArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "taskmanager-${BranchName}-templates-bucket-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: "TaskManager-Templates-Bucket"
        - Key: Purpose
          Value: "CloudFormation Templates and Lambda Layers"
        - Key: Stack
          Value: !Ref "AWS::StackName"

Outputs:
  TemplatesBucket:
    Description: "Name of the templates bucket"
    Value: !Ref RegionalArtifactsBucket
    Export:
      Name: !Sub "TaskManager-${BranchName}-RegionalTemplatesBucket-${AWS::Region}"
