AWSTemplateFormatVersion: "2010-09-09"
Description: "Regional S3 bucket setup"

Parameters:
  BranchName:
    Type: String
    Description: "Branch name for resource naming"

Resources:
  RegionalArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "taskmanager-${BranchName}-templates-bucket-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: "TaskManager-Templates-Bucket"
        - Key: Purpose
          Value: "CloudFormation Templates and Lambda Layers"
        - Key: Stack
          Value: !Ref "AWS::StackName"

  WebECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "taskmanager-web"
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: "MUTABLE"
      Tags:
        - Key: Name
          Value: "TaskManager-Web-ECR"
        - Key: Purpose
          Value: "Container Registry"
        - Key: Stack
          Value: !Ref "AWS::StackName"

Outputs:
  TemplatesBucket:
    Description: "Name of the templates bucket"
    Value: !Ref RegionalArtifactsBucket
    Export:
      Name: !Sub "TaskManager-${BranchName}-RegionalTemplatesBucket-${AWS::Region}"

  WebECRRepositoryUri:
    Description: "ECR repository URI for web application"
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/taskmanager-web"
    Export:
      Name: !Sub "TaskManager-${BranchName}-WebECRRepositoryUri-${AWS::Region}"
