AWSTemplateFormatVersion: "2010-09-09"
Description: "TaskManager Application - API and Web Components"

Parameters:
  Environment:
    Type: String
    Default: main
    Description: "Environment name (typically branch name)"

  ApiCodeBucket:
    Type: String
    Description: "S3 bucket name for API Lambda deployment package"

  WebContainerImage:
    Type: String
    Description: "Container image URI for the web application"

  DeploymentToken:
    Type: String
    Description: "Deployment token to force task definition updates"
    Default: "default"

  DomainName:
    Type: String
    Default: "appcloud.systems"
    Description: "Domain name for SSL certificate"

  HostedZoneId:
    Type: String
    Description: "Route 53 hosted zone ID for the domain"

  TemplatesBucket:
    Type: String
    Description: "S3 bucket name for CloudFormation templates"

Conditions:
  IsUSEast1: !Equals [!Ref AWS::Region, "us-east-1"]

Resources:
  # API Stack (Nested)
  TaskManagerApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatesBucket}/api-template.yaml"
      Parameters:
        Environment: !Ref Environment
        ApiCodeBucket: !Ref ApiCodeBucket
        SharedLambdaRoleArn:
          Fn::ImportValue: !Sub "TaskManager-SharedLambdaRole-${AWS::Region}"
        DatabaseEndpoint: !Sub "taskmanager-cluster.cluster-{{resolve:secretsmanager:taskmanager/database/${Environment}/regional/${AWS::Region}:SecretString:cluster_arn}}.${AWS::Region}.rds.amazonaws.com"
        LambdaSecurityGroupId:
          Fn::ImportValue: !Sub "TaskManager-LambdaSecurityGroup-${AWS::Region}"
        PrivateSubnet1Id:
          Fn::ImportValue: !Sub "TaskManager-PrivateSubnet1-${AWS::Region}"
        PrivateSubnet2Id:
          Fn::ImportValue: !Sub "TaskManager-PrivateSubnet2-${AWS::Region}"
      Tags:
        - Key: Component
          Value: API
        - Key: Environment
          Value: !Ref Environment
      TimeoutInMinutes: 30

  # Web Stack (Nested) - Infrastructure Only
  TaskManagerWebStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: TaskManagerApiStack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${TemplatesBucket}/web-template.yaml"
      Parameters:
        Environment: !Ref Environment
        WebContainerImage: !Ref WebContainerImage
        DeploymentToken: !Ref DeploymentToken
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        SharedLambdaRoleArn:
          Fn::ImportValue: !Sub "TaskManager-SharedLambdaRole-${AWS::Region}"
        VPCId:
          Fn::ImportValue:
            Fn::Sub: "TaskManager-${Environment}-VPC-${AWS::Region}"
        ALBSecurityGroupId:
          Fn::ImportValue:
            Fn::Sub: "TaskManager-ALBSecurityGroup-${AWS::Region}"
        ECSTaskSecurityGroupId:
          Fn::ImportValue:
            Fn::Sub: "TaskManager-ECSTaskSecurityGroup-${AWS::Region}"
        PublicSubnet1Id:
          Fn::ImportValue:
            Fn::Sub: "TaskManager-PublicSubnet1-${AWS::Region}"
        PublicSubnet2Id:
          Fn::ImportValue:
            Fn::Sub: "TaskManager-PublicSubnet2-${AWS::Region}"
        PrivateSubnet1Id:
          Fn::ImportValue:
            Fn::Sub: "TaskManager-PrivateSubnet1-${AWS::Region}"
        PrivateSubnet2Id:
          Fn::ImportValue:
            Fn::Sub: "TaskManager-PrivateSubnet2-${AWS::Region}"
        ECSClusterName:
          Fn::ImportValue:
            Fn::Sub: "TaskManager-ECSCluster"
        DatabaseEndpoint: !Sub "taskmanager-cluster.cluster-{{resolve:secretsmanager:taskmanager/database/${Environment}/regional/${AWS::Region}:SecretString:cluster_arn}}.${AWS::Region}.rds.amazonaws.com"
      Tags:
        - Key: Component
          Value: Web-Infrastructure
        - Key: Environment
          Value: !Ref Environment
      TimeoutInMinutes: 30

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !GetAtt TaskManagerApiStack.Outputs.ApiEndpoint
    Export:
      Name: !Sub "TaskManager-${Environment}-ApiEndpoint"

  ApiLambdaFunctionName:
    Description: "API Lambda function name"
    Value: !GetAtt TaskManagerApiStack.Outputs.ApiLambdaFunctionName
    Export:
      Name: !Sub "TaskManager-${Environment}-ApiLambdaFunction"

  WebEndpoint:
    Description: "Web application endpoint URL"
    Value: !GetAtt TaskManagerWebStack.Outputs.WebEndpoint
    Export:
      Name: !Sub "TaskManager-${Environment}-WebEndpoint"

  WebLoadBalancerDNS:
    Description: "Web Load Balancer DNS name"
    Value: !GetAtt TaskManagerWebStack.Outputs.WebLoadBalancerDNS
    Export:
      Name: !Sub "TaskManager-${Environment}-WebLoadBalancerDNS"

  WebTaskDefinition:
    Description: "Web ECS task definition"
    Value: !GetAtt TaskManagerWebStack.Outputs.WebTaskDefinition
    Export:
      Name: !Sub "TaskManager-${Environment}-WebTaskDefinition"

  WebServiceName:
    Description: "Web ECS service name"
    Value: !GetAtt TaskManagerWebStack.Outputs.WebServiceName
    Export:
      Name: !Sub "TaskManager-${Environment}-WebService"

  BranchEnvironment:
    Description: "Branch environment name"
    Value: !Ref Environment
    Export:
      Name: !Sub "TaskManager-${Environment}-Environment"

  DeploymentSummary:
    Description: "Deployment summary"
    Value: !Sub |
      TaskManager ${Environment} API and Web deployed successfully!

      API Endpoint: ${TaskManagerApiStack.Outputs.ApiEndpoint}
      Web Application: https://${Environment}.${DomainName}

      API is running on AWS Lambda with API Gateway.
      Web is running on AWS ECS containers with Application Load Balancer.
